# Generated by Django 2.2.4 on 2019-09-06 20:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=255)),
                ('question_is_multiple_choice', models.BooleanField(default=False)),
                ('question_is_numeric', models.BooleanField(default=False)),
                ('question_numeric_range_upper_bound', models.IntegerField(blank=True, null=True)),
                ('question_numeric_range_lower_bound', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('label', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_description', models.CharField(max_length=1023)),
                ('group_age_lower_bound', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)])),
                ('group_age_upper_bound', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)])),
                ('group_target_size', models.IntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name_plural': 'Statistical Groups',
            },
        ),
        migrations.AlterModelOptions(
            name='surveybase',
            options={'verbose_name': 'Survey Basis', 'verbose_name_plural': 'Survey Bases'},
        ),
        migrations.AddField(
            model_name='profile',
            name='can_create_org',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuestionCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_catalog_name', models.CharField(max_length=255)),
                ('question_catalog_description', models.CharField(blank=True, max_length=1023, null=True)),
                ('question_catalog_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Organization')),
            ],
            options={
                'verbose_name_plural': 'Question Catalogs',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1023)),
                ('answer_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_date', models.DateTimeField(default=datetime.datetime.now)),
                ('answer_stat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.StatisticalGroup')),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
            ],
            options={
                'verbose_name': 'Question Answer',
                'verbose_name_plural': 'Question Answers',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswerPossibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1023)),
                ('answer_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('related_question', models.ManyToManyField(to='survey.Question')),
            ],
            options={
                'verbose_name_plural': 'Multiple Choice Answer Possbilities',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.TextField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='survey.Room')),
            ],
        ),
    ]
